"""Universal syntax and policy vocabulary for Nano Intent."""

from __future__ import annotations

from ..lexicon import Catalog


def _aliases(role: str, canonical: str, *aliases: str):
    return tuple((alias, role, canonical) for alias in aliases)


CORE_CATALOG = Catalog(
    identity="core",
    version="0.1.0",
    precedence=10,
    aliases=(
        *_aliases("imperative", "open", "open", "show", "view"),
        *_aliases("imperative", "focus", "focus"),
        *_aliases("imperative", "switch", "switch"),
        *_aliases("imperative", "add", "add"),
        *_aliases("imperative", "remove", "remove"),
        *_aliases("interrogative", "who", "who"),
        *_aliases("interrogative", "what", "what"),
        *_aliases("interrogative", "when", "when"),
        *_aliases("interrogative", "where", "where"),
        *_aliases("interrogative", "why", "why"),
        *_aliases("interrogative", "how", "how"),
        *_aliases("interrogative", "which", "which"),
        *_aliases("analytical", "explain", "explain"),
        *_aliases("analytical", "describe", "describe"),
        *_aliases("analytical", "compare", "compare"),
        *_aliases("analytical", "summarize", "summarize", "summarise"),
        *_aliases("analytical", "assess", "assess"),
        *_aliases("analytical", "forecast", "predict", "prediction", "predictions", "forecast", "forecasts"),
        *_aliases("analytical", "scenario", "scenario", "scenarios"),
        *_aliases("analytical", "risk", "risk", "risks"),
        *_aliases("external_action", "send", "send"),
        *_aliases("external_action", "publish", "publish"),
        *_aliases("external_action", "post", "post"),
        *_aliases("external_action", "share", "share"),
        *_aliases("external_action", "export", "export"),
        *_aliases("external_action", "change", "change"),
        *_aliases("external_action", "delete", "delete"),
        *_aliases("external_action", "execute", "execute"),
        *_aliases("trade", "buy", "buy"),
        *_aliases("trade", "sell", "sell"),
        *_aliases("trade", "trade", "trade"),
        *_aliases("conjunction", "and", "and", "then"),
        *_aliases("comparison", "than", "than", "versus", "vs"),
        *_aliases("negation", "not", "not", "never", "without"),
        *_aliases("qualifier", "higher", "higher"),
        *_aliases("qualifier", "lower", "lower"),
        *_aliases("qualifier", "move", "move", "movement"),
        *_aliases("ui_noun", "tile", "tile", "panel", "tab"),
        *_aliases(
            "filler",
            "filler",
            "a",
            "an",
            "the",
            "is",
            "are",
            "be",
            "to",
            "of",
            "for",
            "me",
            "my",
            "just",
            "do",
            "over",
            "s",
            "this",
            "that",
            "it",
            "on",
            "in",
            "at",
            "from",
            "with",
        ),
        *_aliases("time", "today", "today"),
        *_aliases("time", "tomorrow", "tomorrow"),
        *_aliases("time", "next", "next"),
        *_aliases("time", "previous", "previous", "prior", "last"),
        *_aliases("time", "since", "since"),
        *_aliases("time", "open", "open"),
        *_aliases("time_unit", "day", "day", "days"),
        *_aliases("time_unit", "week", "week", "weeks"),
        *_aliases("time_unit", "month", "month", "months"),
        *_aliases("time_unit", "quarter", "quarter", "quarters", "qtr", "qtrs"),
        *_aliases("time_unit", "year", "year", "years"),
    ),
)

__all__ = ["CORE_CATALOG"]
